pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        ACCOUNT_ID = "713386558285"
        ECR_REPO = "streamlit-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
        ECR_URI = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }

    options {
        timestamps()
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo "Cloning repository..."
                git branch: 'main', url: 'https://github.com/tejupatil2410-gif/fullstack-cicd-aws-eks.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image..."
                sh """
                docker build -t ${ECR_REPO}:${IMAGE_TAG} \
                -f app/backend/Dockerfile app/backend
                """
            }
        }

        stage('Login to Amazon ECR') {
            steps {
                echo "Authenticating with ECR..."
                sh """
                aws ecr get-login-password --region ${AWS_REGION} | \
                docker login --username AWS --password-stdin ${ECR_URI}
                """
            }
        }

        stage('Tag Docker Image') {
            steps {
                echo "Tagging image for ECR..."
                sh """
                docker tag ${ECR_REPO}:${IMAGE_TAG} \
                ${ECR_URI}/${ECR_REPO}:${IMAGE_TAG}
                """
            }
        }

        stage('Push Image to ECR') {
            steps {
                echo "Pushing image to ECR..."
                sh """
                docker push ${ECR_URI}/${ECR_REPO}:${IMAGE_TAG}
                """
            }
        }
    }

    post {
        success {
            echo "✅ CI SUCCESS: Docker image built and pushed to ECR!"
        }
        failure {
            echo "❌ CI FAILED: Check console logs."
        }
        always {
            echo "Cleaning up local Docker images..."
            sh """
            docker rmi ${ECR_REPO}:${IMAGE_TAG} || true
            docker rmi ${ECR_URI}/${ECR_REPO}:${IMAGE_TAG} || true
            """
        }
    }
}